server:
  port: 8081
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        name: SESSION
        path: /
        http-only: true
        secure: false

spring:
  application:
    name: auth-service

  session:
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: on-save

  redis:
    host: redis
    port: 6379

logging:
  level:
    org.springframework.data.redis: DEBUG

jwt:
  token: ${JWT_TOKEN}