server:
  port: 8081
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        name: SESSION
        domain: localhost
        path: /
        http-only: true
        secure: false

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost/mikhailpoizon_test
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        format_sql: true

  session:
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: on-save

  redis:
    host: localhost
    port: 6379