server:
  port: 8082
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        name: SESSION
        domain: localhost
        path: /
        http-only: true
        secure: false

spring:
  application:
    name: profile-service

  datasource:
    url: jdbc:postgresql://localhost/mikhailpoizon_test
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        format_sql: true

  session:
    store-type: redis

  redis:
    host: localhost
    port: 6379
