server:
  port: 8085

spring:
  application:
    name: mail-service
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: mail-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      retries: 3
      properties:
        spring.json.trusted.packages: "*"
  mail:
    host: smtp.gmail.com
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    port: 587
    protocol: smtps
    debug: true
    allow-bean-definition-overriding: true
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
