server:
  port: 0

spring:
  application:
    name: mail-service
  cloud:
    stream:
      bindings:
        mailConfirmConsumer-in-0:
          destination: confirm-mail-event-topic
      kafka:
        binder:
          brokers: kafka:9092
  mail:
    host: smtp.gmail.com
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    port: 587
    debug: true
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/