server:
  port: 0

spring:
  application:
    name: mail-service
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: mail-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      retries: 3
      properties:
        spring.json.trusted.packages: "*"
  mail:
    host: smtp.gmail.com
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    port: 587
    debug: true
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/