server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: profile-service
          uri: http://localhost:8082
          predicates:
            - Path=/profile/**
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**