server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: fundament-service
          uri: http://localhost:8081
          predicates:
            - Path=
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1