server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: fundament-service
          uri: http://localhost:8081
          predicates:
            - Path=/main/**
          filters:
            - StripPrefix=1