server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: root-to-feed
          uri: http://feed-service:8084
          predicates:
            - Path=/
          filters:
            - RedirectTo=302, /feed
        - id: frontend
          uri: lb://frontend-service
          predicates:
            - Path=/css/**, /js/**, /images/**, /favicon.ico
        - id: profile-service
          uri: http://profile-service:8082
          predicates:
            - Path=/profile/**
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
        - id: database-service
          uri: http://database-service:8083
          predicates:
            - Path=/api/**
        - id: feed-service
          uri: http://feed-service:8084
          predicates:
            - Path=/feed/**