server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: profile-service
          uri: http://profile-service:8082
          predicates:
            - Path=/profile/**
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
        - id: database-service
          uri: http://database-service:8083
          predicates:
            - Path=/api/**