server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: root-to-feed
          uri: lb://feed-service
          predicates:
            - Path=/
          filters:
            - RedirectTo=302, /feed
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/profile/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: database-service
          uri: lb://database-service
          predicates:
            - Path=/api/**
        - id: feed-service
          uri: lb://feed-service
          predicates:
            - Path=/feed/**
        - id: service-discovery
          uri: lb://service-discovery
          predicates:
            - Path=/eureka/

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/