server:
  port: 8082
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        name: SESSION
        path: /
        http-only: true
        secure: false

spring:
  application:
    name: profile-service
  session:
    store-type: redis
  redis:
    host: redis
    port: 6379

logging:
  level:
    org.springframework.data.redis: DEBUG

jwt:
  token: ${JWT_TOKEN}