server:
  port: 0
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        name: SESSION
        path: /
        http-only: true
        secure: false

spring:
  application:
    name: feed-service
  session:
    store-type: redis
  redis:
    host: redis
    port: 6379
  eureka:
    client:
      service-url:
        defaultZone: http://service-discovery:8761/eureka/

logging:
  level:
    org.springframework.data.redis: DEBUG

jwt:
  token: JWT_TOKEN