server:
  port: 0
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        name: SESSION
        path: /
        http-only: true
        secure: false

spring:
  application:
    name: admin-service
  session:
    store-type: redis
  redis:
    host: redis
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  token: ${JWT_TOKEN}